#include "pythontarget.h"
#include <limits.h>
#include "include/core/platform.h"
#include "include/api/api.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/threaded/scheduler.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
// Code generated by the Lingua Franca compiler from:
// file://mnt/c/Users/jacky/Desktop/simple_multi/src/subinterpreter.lf
#define LOG_LEVEL 2
#define TARGET_FILES_DIRECTORY "/mnt/c/Users/jacky/Desktop/simple_multi/src-gen/subinterpreter"

int main(int argc, const char* argv[]) {
    return lf_reactor_c_main(argc, argv);
}
void _lf_set_default_command_line_options() {}
#include "_clientreactor.h"
#include "_serverreactor.h"
#include "__lf_gendelay_0.h"
#include "_subinterpreter_main.h"
typedef enum {
    subinterpreter_main,
    _num_enclaves
} _enclave_id;
// The global array of environments associated with each enclave
environment_t envs[_num_enclaves];
// 'Create' and initialize the environments in the program
void _lf_create_environments() {
    environment_init(&envs[subinterpreter_main],subinterpreter_main,_lf_number_of_workers,0,3,0,0,5,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) envs;
   return _num_enclaves;
}
// No watchdogs found.
typedef void watchdog_t;
watchdog_t* _lf_watchdogs = NULL;
int _lf_watchdog_count = 0;
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[_num_enclaves] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _subinterpreter_main_main_self_t* subinterpreter_main_self[1];
    SUPPRESS_UNUSED_WARNING(subinterpreter_main_self);
    _clientreactor_self_t* subinterpreter_client_self[2];
    SUPPRESS_UNUSED_WARNING(subinterpreter_client_self);
    _serverreactor_self_t* subinterpreter_server_self[1];
    SUPPRESS_UNUSED_WARNING(subinterpreter_server_self);
    __lf_gendelay_0_self_t* subinterpreter_delay_self[1];
    SUPPRESS_UNUSED_WARNING(subinterpreter_delay_self);
    // ***** Start initializing subinterpreter of class subinterpreter
    subinterpreter_main_self[0] = new__subinterpreter_main();
    subinterpreter_main_self[0]->base.environment = &envs[subinterpreter_main];
    subinterpreter_main_self[0]->_lf_name = "subinterpreter_main_lf";
    SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    // initialize the index for subinterperter
    int interp_index = 0;
    
    // Reactor is a bank. Iterate over bank members.
    for (int subinterpreter_client_i = 0; subinterpreter_client_i < 2; subinterpreter_client_i++) {
        // ***** Start initializing subinterpreter.client of class clientReactor
        subinterpreter_client_self[subinterpreter_client_i] = new__clientreactor(interp_index);
        interp_index += 1;
        subinterpreter_client_self[subinterpreter_client_i]->base.environment = &envs[subinterpreter_main];
        subinterpreter_client_self[subinterpreter_client_i]->_lf_name = "subinterpreter_client_lf";
        subinterpreter_client_self[subinterpreter_client_i]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            subinterpreter_client_self[subinterpreter_client_i]->_lf_name,
            subinterpreter_client_i,
            "reaction_function_0");
        if(subinterpreter_client_self[subinterpreter_client_i]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        subinterpreter_client_self[subinterpreter_client_i]->_lf_py_reaction_function_1 = 
        get_python_function("__main__", 
            subinterpreter_client_self[subinterpreter_client_i]->_lf_name,
            subinterpreter_client_i,
            "reaction_function_1");
        if(subinterpreter_client_self[subinterpreter_client_i]->_lf_py_reaction_function_1 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_1");
        }
        // width of -2 indicates that it is not a multiport.
        subinterpreter_client_self[subinterpreter_client_i]->_lf_updated_parameters_width = -2;
        // width of -2 indicates that it is not a multiport.
        subinterpreter_client_self[subinterpreter_client_i]->_lf_global_parameters_width = -2;
        envs[subinterpreter_main].startup_reactions[startup_reaction_count[subinterpreter_main]++] = &subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_0.deadline = NEVER;
        subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing subinterpreter.client
    }
    {
        // ***** Start initializing subinterpreter.server of class serverReactor
        subinterpreter_server_self[0] = new__serverreactor(interp_index);
        interp_index += 1;
        subinterpreter_server_self[0]->base.environment = &envs[subinterpreter_main];
        subinterpreter_server_self[0]->_lf_name = "subinterpreter_server_lf";
        subinterpreter_server_self[0]->_lf_py_reaction_function_0 = 
        get_python_function("__main__", 
            subinterpreter_server_self[0]->_lf_name,
            0,
            "reaction_function_0");
        if(subinterpreter_server_self[0]->_lf_py_reaction_function_0 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_0");
        }
        subinterpreter_server_self[0]->_lf_py_reaction_function_1 = 
        get_python_function("__main__", 
            subinterpreter_server_self[0]->_lf_name,
            0,
            "reaction_function_1");
        if(subinterpreter_server_self[0]->_lf_py_reaction_function_1 == NULL) {
            lf_print_error_and_exit("Could not load function reaction_function_1");
        }
        // width of -2 indicates that it is not a multiport.
        subinterpreter_server_self[0]->_lf_global_parameters_width = -2;
        subinterpreter_server_self[0]->_lf_updated_parameters_width = 2;
        // Allocate memory for multiport inputs.
        subinterpreter_server_self[0]->_lf_updated_parameters = (_serverreactor_updated_parameters_t**)_lf_allocate(
                2, sizeof(_serverreactor_updated_parameters_t*),
                &subinterpreter_server_self[0]->base.allocations); 
        // Set inputs by default to an always absent default input.
        for (int i = 0; i < 2; i++) {
            subinterpreter_server_self[0]->_lf_updated_parameters[i] = &subinterpreter_server_self[0]->_lf_default__updated_parameters;
        }
        envs[subinterpreter_main].startup_reactions[startup_reaction_count[subinterpreter_main]++] = &subinterpreter_server_self[0]->_lf__reaction_0;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
    
        subinterpreter_server_self[0]->_lf__reaction_0.deadline = NEVER;
        subinterpreter_server_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing subinterpreter.server
    }
    // Reactor is a bank. Iterate over bank members.
    for (int subinterpreter_delay_i = 0; subinterpreter_delay_i < 1; subinterpreter_delay_i++) {
        // ***** Start initializing subinterpreter.delay of class _lf_GenDelay_0
        subinterpreter_delay_self[0] = new___lf_gendelay_0();
        subinterpreter_delay_self[0]->base.environment = &envs[subinterpreter_main];
        subinterpreter_delay_self[0]->_lf_name = "subinterpreter_delay_lf";
        // width of -2 indicates that it is not a multiport.
        subinterpreter_delay_self[0]->_lf_out_width = -2;
        // width of -2 indicates that it is not a multiport.
        subinterpreter_delay_self[0]->_lf_inp_width = -2;
        SUPPRESS_UNUSED_WARNING(_lf_watchdog_count);
        // Initializing action subinterpreter.delay.act
        subinterpreter_delay_self[0]->_lf__act.offset = 0;
        subinterpreter_delay_self[0]->_lf__act.period = -1;
        subinterpreter_delay_self[0]->_lf__act.mode = NULL;
        _lf_initialize_template((token_template_t*)
                &(subinterpreter_delay_self[0]->_lf__act),
        0);
        subinterpreter_delay_self[0]->_lf__act.status = absent;
        subinterpreter_delay_self[0]->_lf__reaction_0.deadline = NEVER;
        subinterpreter_delay_self[0]->_lf__reaction_1.deadline = NEVER;
        //***** End initializing subinterpreter.delay
    }
    //***** End initializing subinterpreter
    // **** Start deferred initialize for subinterpreter
    {
    
    
    
        // **** Start deferred initialize for subinterpreter.client
        // Reactor is a bank. Iterate over bank members.
        for (int subinterpreter_client_i = 0; subinterpreter_client_i < 2; subinterpreter_client_i++) {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of subinterpreter.client.
            subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of subinterpreter.client
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of subinterpreter.client.
            subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &subinterpreter_client_self[subinterpreter_client_i]->base.allocations);
            subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &subinterpreter_client_self[subinterpreter_client_i]->base.allocations);
            subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &subinterpreter_client_self[subinterpreter_client_i]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_1.output_produced[count++] = &subinterpreter_client_self[subinterpreter_client_i]->_lf_updated_parameters.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of subinterpreter.client
        
        }
        // **** End of deferred initialize for subinterpreter.client
        // **** Start deferred initialize for subinterpreter.server
        {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of subinterpreter.server.
            subinterpreter_server_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            subinterpreter_server_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &subinterpreter_server_self[0]->base.allocations);
            subinterpreter_server_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &subinterpreter_server_self[0]->base.allocations);
            subinterpreter_server_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &subinterpreter_server_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    subinterpreter_server_self[0]->_lf__reaction_0.output_produced[count++] = &subinterpreter_server_self[0]->_lf_global_parameters.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of subinterpreter.server
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of subinterpreter.server.
            subinterpreter_server_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            subinterpreter_server_self[0]->_lf__reaction_1.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &subinterpreter_server_self[0]->base.allocations);
            subinterpreter_server_self[0]->_lf__reaction_1.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &subinterpreter_server_self[0]->base.allocations);
            subinterpreter_server_self[0]->_lf__reaction_1.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &subinterpreter_server_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    subinterpreter_server_self[0]->_lf__reaction_1.output_produced[count++] = &subinterpreter_server_self[0]->_lf_global_parameters.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of subinterpreter.server
        
        }
        // **** End of deferred initialize for subinterpreter.server
        // **** Start deferred initialize for subinterpreter.delay
        // Reactor is a bank. Iterate over bank members.
        for (int subinterpreter_delay_i = 0; subinterpreter_delay_i < 1; subinterpreter_delay_i++) {
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of subinterpreter.delay.
            subinterpreter_delay_self[0]->_lf__reaction_0.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            subinterpreter_delay_self[0]->_lf__reaction_0.triggers = (trigger_t***)_lf_allocate(
                    1, sizeof(trigger_t**),
                    &subinterpreter_delay_self[0]->base.allocations);
            subinterpreter_delay_self[0]->_lf__reaction_0.triggered_sizes = (int*)_lf_allocate(
                    1, sizeof(int),
                    &subinterpreter_delay_self[0]->base.allocations);
            subinterpreter_delay_self[0]->_lf__reaction_0.output_produced = (bool**)_lf_allocate(
                    1, sizeof(bool*),
                    &subinterpreter_delay_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    subinterpreter_delay_self[0]->_lf__reaction_0.output_produced[count++] = &subinterpreter_delay_self[0]->_lf_out.is_present;
                }
            }
            
            // ** End initialization for reaction 0 of subinterpreter.delay
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of subinterpreter.delay.
            subinterpreter_delay_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of subinterpreter.delay
        
        }
        // **** End of deferred initialize for subinterpreter.delay
    }
    // **** End of deferred initialize for subinterpreter
    // **** Start non-nested deferred initialize for subinterpreter
    {
    
    
    
        // **** Start non-nested deferred initialize for subinterpreter.client
        // Reactor is a bank. Iterate over bank members.
        for (int subinterpreter_client_i = 0; subinterpreter_client_i < 2; subinterpreter_client_i++) {
        
            // For reference counting, set num_destinations for port subinterpreter.client.updated_parameters.
            // Iterate over range subinterpreter.client.updated_parameters(0,2)->[subinterpreter.server.updated_parameters(0,2)].
            {
                int range_start[] =  { 0, 0 };
                int range_radixes[] = { 1, 2 };
                int permutation[] = { 0, 1 };
                mixed_radix_int_t range_mr = {
                    2,
                    range_start,
                    range_radixes,
                    permutation
                };
                for (int range_count = 0; range_count < 0 + 2; range_count++) {
                    int src_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = range_mr.digits[0]; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = range_mr.digits[1]; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    subinterpreter_client_self[src_runtime]->_lf_updated_parameters._base.num_destinations = 1;
                    subinterpreter_client_self[src_runtime]->_lf_updated_parameters._base.source_reactor = (self_base_t*)subinterpreter_client_self[src_runtime];
                    mixed_radix_incr(&range_mr);
                }
            }
            {
                int triggers_index[2] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range subinterpreter.client.updated_parameters(0,2)->[subinterpreter.server.updated_parameters(0,2)].
                {
                    int range_start[] =  { 0, 0 };
                    int range_radixes[] = { 1, 2 };
                    int permutation[] = { 0, 1 };
                    mixed_radix_int_t range_mr = {
                        2,
                        range_start,
                        range_radixes,
                        permutation
                    };
                    for (int range_count = 0; range_count < 0 + 2; range_count++) {
                        int src_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                        SUPPRESS_UNUSED_WARNING(src_runtime);
                        int src_channel = range_mr.digits[0]; // Channel index.
                        SUPPRESS_UNUSED_WARNING(src_channel);
                        int src_bank = range_mr.digits[1]; // Bank index.
                        SUPPRESS_UNUSED_WARNING(src_bank);
                        // Reaction 1 of subinterpreter.client triggers 1 downstream reactions
                        // through port subinterpreter.client.updated_parameters.
                        subinterpreter_client_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                        // For reaction 1 of subinterpreter.client, allocate an
                        // array of trigger pointers for downstream reactions through port subinterpreter.client.updated_parameters
                        trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                                1, sizeof(trigger_t*),
                                &subinterpreter_client_self[src_runtime]->base.allocations); 
                        subinterpreter_client_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                        mixed_radix_incr(&range_mr);
                    }
                }
                for (int i = 0; i < 2; i++) triggers_index[i] = 0;
                // Iterate over ranges subinterpreter.client.updated_parameters(0,2)->[subinterpreter.server.updated_parameters(0,2)] and subinterpreter.server.updated_parameters(0,2).
                {
                    int src_start[] =  { 0, 0 };
                    int src_value[] =  { 0, 0 }; // Will be incremented.
                    int src_radixes[] = { 1, 2 };
                    int src_permutation[] = { 0, 1 };
                    mixed_radix_int_t src_range_mr = {
                        2,
                        src_value,
                        src_radixes,
                        src_permutation
                    };
                    // Iterate over range subinterpreter.server.updated_parameters(0,2).
                    {
                        int range_start[] =  { 0, 0 };
                        int range_radixes[] = { 2, 1 };
                        int permutation[] = { 0, 1 };
                        mixed_radix_int_t range_mr = {
                            2,
                            range_start,
                            range_radixes,
                            permutation
                        };
                        for (int range_count = 0; range_count < 0 + 2; range_count++) {
                            int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                            SUPPRESS_UNUSED_WARNING(dst_runtime);
                            int dst_channel = range_mr.digits[0]; // Channel index.
                            SUPPRESS_UNUSED_WARNING(dst_channel);
                            int dst_bank = range_mr.digits[1]; // Bank index.
                            SUPPRESS_UNUSED_WARNING(dst_bank);
                            int src_runtime = mixed_radix_parent(&src_range_mr, 1); // Runtime index.
                            SUPPRESS_UNUSED_WARNING(src_runtime);
                            int src_channel = src_range_mr.digits[0]; // Channel index.
                            SUPPRESS_UNUSED_WARNING(src_channel);
                            int src_bank = src_range_mr.digits[1]; // Bank index.
                            SUPPRESS_UNUSED_WARNING(src_bank);
                            // Point to destination port subinterpreter.server.updated_parameters's trigger struct.
                            subinterpreter_client_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &subinterpreter_server_self[dst_runtime]->_lf__updated_parameters;
                            mixed_radix_incr(&src_range_mr);
                            if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                                // Start over with the source.
                                for (int i = 0; i < src_range_mr.size; i++) {
                                    src_range_mr.digits[i] = src_start[i];
                                }
                            }
                            mixed_radix_incr(&range_mr);
                        }
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for subinterpreter.client
        // **** Start non-nested deferred initialize for subinterpreter.server
        {
        
            // For reference counting, set num_destinations for port subinterpreter.server.global_parameters.
            // Iterate over range subinterpreter.server.global_parameters(0,1)->[subinterpreter.delay.inp(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                subinterpreter_server_self[src_runtime]->_lf_global_parameters._base.num_destinations = 1;
                subinterpreter_server_self[src_runtime]->_lf_global_parameters._base.source_reactor = (self_base_t*)subinterpreter_server_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range subinterpreter.server.global_parameters(0,1)->[subinterpreter.delay.inp(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of subinterpreter.server triggers 1 downstream reactions
                    // through port subinterpreter.server.global_parameters.
                    subinterpreter_server_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 0 of subinterpreter.server, allocate an
                    // array of trigger pointers for downstream reactions through port subinterpreter.server.global_parameters
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &subinterpreter_server_self[src_runtime]->base.allocations); 
                    subinterpreter_server_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges subinterpreter.server.global_parameters(0,1)->[subinterpreter.delay.inp(0,1)] and subinterpreter.delay.inp(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range subinterpreter.delay.inp(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port subinterpreter.delay.inp's trigger struct.
                        subinterpreter_server_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &subinterpreter_delay_self[dst_runtime]->_lf__inp;
                    }
                }
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range subinterpreter.server.global_parameters(0,1)->[subinterpreter.delay.inp(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of subinterpreter.server triggers 1 downstream reactions
                    // through port subinterpreter.server.global_parameters.
                    subinterpreter_server_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of subinterpreter.server, allocate an
                    // array of trigger pointers for downstream reactions through port subinterpreter.server.global_parameters
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            1, sizeof(trigger_t*),
                            &subinterpreter_server_self[src_runtime]->base.allocations); 
                    subinterpreter_server_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges subinterpreter.server.global_parameters(0,1)->[subinterpreter.delay.inp(0,1)] and subinterpreter.delay.inp(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range subinterpreter.delay.inp(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port subinterpreter.delay.inp's trigger struct.
                        subinterpreter_server_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &subinterpreter_delay_self[dst_runtime]->_lf__inp;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for subinterpreter.server
        // **** Start non-nested deferred initialize for subinterpreter.delay
        // Reactor is a bank. Iterate over bank members.
        for (int subinterpreter_delay_i = 0; subinterpreter_delay_i < 1; subinterpreter_delay_i++) {
        
            // For reference counting, set num_destinations for port subinterpreter.delay.out.
            // Iterate over range subinterpreter.delay.out(0,1)->[subinterpreter.client.global_parameters(0,1), subinterpreter.client.global_parameters(1,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                subinterpreter_delay_self[src_runtime]->_lf_out._base.num_destinations = 2;
                subinterpreter_delay_self[src_runtime]->_lf_out._base.source_reactor = (self_base_t*)subinterpreter_delay_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range subinterpreter.delay.out(0,1)->[subinterpreter.client.global_parameters(0,1), subinterpreter.client.global_parameters(1,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 0 of subinterpreter.delay triggers 2 downstream reactions
                    // through port subinterpreter.delay.out.
                    subinterpreter_delay_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 2;
                    // For reaction 0 of subinterpreter.delay, allocate an
                    // array of trigger pointers for downstream reactions through port subinterpreter.delay.out
                    trigger_t** trigger_array = (trigger_t**)_lf_allocate(
                            2, sizeof(trigger_t*),
                            &subinterpreter_delay_self[src_runtime]->base.allocations); 
                    subinterpreter_delay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges subinterpreter.delay.out(0,1)->[subinterpreter.client.global_parameters(0,1), subinterpreter.client.global_parameters(1,1)] and subinterpreter.client.global_parameters(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range subinterpreter.client.global_parameters(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port subinterpreter.client.global_parameters's trigger struct.
                        subinterpreter_delay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &subinterpreter_client_self[dst_runtime]->_lf__global_parameters;
                    }
                }
                // Iterate over ranges subinterpreter.delay.out(0,1)->[subinterpreter.client.global_parameters(0,1), subinterpreter.client.global_parameters(1,1)] and subinterpreter.client.global_parameters(1,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range subinterpreter.client.global_parameters(1,1).
                    {
                        int dst_runtime = 1; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 1; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Point to destination port subinterpreter.client.global_parameters's trigger struct.
                        subinterpreter_delay_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][1] = &subinterpreter_client_self[dst_runtime]->_lf__global_parameters;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for subinterpreter.delay
    }
    // **** End of non-nested deferred initialize for subinterpreter
    // Connect inputs and outputs for reactor subinterpreter.
    // Connect inputs and outputs for reactor subinterpreter.client.
    // Connect subinterpreter.client.updated_parameters(0,2)->[subinterpreter.server.updated_parameters(0,2)] to port subinterpreter.server.updated_parameters(0,2)
    // Iterate over ranges subinterpreter.client.updated_parameters(0,2)->[subinterpreter.server.updated_parameters(0,2)] and subinterpreter.server.updated_parameters(0,2).
    {
        int src_start[] =  { 0, 0 };
        int src_value[] =  { 0, 0 }; // Will be incremented.
        int src_radixes[] = { 1, 2 };
        int src_permutation[] = { 0, 1 };
        mixed_radix_int_t src_range_mr = {
            2,
            src_value,
            src_radixes,
            src_permutation
        };
        // Iterate over range subinterpreter.server.updated_parameters(0,2).
        {
            int range_start[] =  { 0, 0 };
            int range_radixes[] = { 2, 1 };
            int permutation[] = { 0, 1 };
            mixed_radix_int_t range_mr = {
                2,
                range_start,
                range_radixes,
                permutation
            };
            for (int range_count = 0; range_count < 0 + 2; range_count++) {
                int dst_runtime = mixed_radix_parent(&range_mr, 1); // Runtime index.
                SUPPRESS_UNUSED_WARNING(dst_runtime);
                int dst_channel = range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(dst_channel);
                int dst_bank = range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(dst_bank);
                int src_runtime = mixed_radix_parent(&src_range_mr, 1); // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = src_range_mr.digits[0]; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = src_range_mr.digits[1]; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                subinterpreter_server_self[dst_runtime]->_lf_updated_parameters[dst_channel] = (_serverreactor_updated_parameters_t*)&subinterpreter_client_self[src_runtime]->_lf_updated_parameters;
                mixed_radix_incr(&src_range_mr);
                if (mixed_radix_to_int(&src_range_mr) >= 0 + 2) {
                    // Start over with the source.
                    for (int i = 0; i < src_range_mr.size; i++) {
                        src_range_mr.digits[i] = src_start[i];
                    }
                }
                mixed_radix_incr(&range_mr);
            }
        }
    }
    // Connect inputs and outputs for reactor subinterpreter.server.
    // Connect subinterpreter.server.global_parameters(0,1)->[subinterpreter.delay.inp(0,1)] to port subinterpreter.delay.inp(0,1)
    // Iterate over ranges subinterpreter.server.global_parameters(0,1)->[subinterpreter.delay.inp(0,1)] and subinterpreter.delay.inp(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range subinterpreter.delay.inp(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            subinterpreter_delay_self[dst_runtime]->_lf_inp = (__lf_gendelay_0_inp_t*)&subinterpreter_server_self[src_runtime]->_lf_global_parameters;
        }
    }
    // Connect inputs and outputs for reactor subinterpreter.delay.
    // Connect subinterpreter.delay.out(0,1)->[subinterpreter.client.global_parameters(0,1), subinterpreter.client.global_parameters(1,1)] to port subinterpreter.client.global_parameters(0,1)
    // Iterate over ranges subinterpreter.delay.out(0,1)->[subinterpreter.client.global_parameters(0,1), subinterpreter.client.global_parameters(1,1)] and subinterpreter.client.global_parameters(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range subinterpreter.client.global_parameters(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            subinterpreter_client_self[dst_runtime]->_lf_global_parameters = (_clientreactor_global_parameters_t*)&subinterpreter_delay_self[src_runtime]->_lf_out;
        }
    }
    // Connect subinterpreter.delay.out(0,1)->[subinterpreter.client.global_parameters(0,1), subinterpreter.client.global_parameters(1,1)] to port subinterpreter.client.global_parameters(1,1)
    // Iterate over ranges subinterpreter.delay.out(0,1)->[subinterpreter.client.global_parameters(0,1), subinterpreter.client.global_parameters(1,1)] and subinterpreter.client.global_parameters(1,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range subinterpreter.client.global_parameters(1,1).
        {
            int dst_runtime = 1; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 1; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            subinterpreter_client_self[dst_runtime]->_lf_global_parameters = (_clientreactor_global_parameters_t*)&subinterpreter_delay_self[src_runtime]->_lf_out;
        }
    }
    // Reactor is a bank. Iterate over bank members.
    for (int subinterpreter_client_i = 0; subinterpreter_client_i < 2; subinterpreter_client_i++) {
    }
    {
    }
    // Reactor is a bank. Iterate over bank members.
    for (int subinterpreter_delay_i = 0; subinterpreter_delay_i < 1; subinterpreter_delay_i++) {
        // Reactor is a bank. Iterate over bank members.
        for (int subinterpreter_delay_i = 0; subinterpreter_delay_i < 1; subinterpreter_delay_i++) {
            // Add action subinterpreter.delay.act to array of is_present fields.
            envs[subinterpreter_main].is_present_fields[0] 
                    = &subinterpreter_delay_self[0]->_lf_act.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add action subinterpreter.delay.act to array of intended_tag fields.
            envs[subinterpreter_main]._lf_intended_tag_fields[0] 
                    = &subinterpreter_delay_self[0]->_lf_act.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        // Reactor is a bank. Iterate over bank members.
        for (int subinterpreter_client_i = 0; subinterpreter_client_i < 2; subinterpreter_client_i++) {
            // Add port subinterpreter.client.updated_parameters to array of is_present fields.
            envs[subinterpreter_main].is_present_fields[1 + count] = &subinterpreter_client_self[subinterpreter_client_i]->_lf_updated_parameters.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port subinterpreter.client.updated_parameters to array of intended_tag fields.
            envs[subinterpreter_main]._lf_intended_tag_fields[1 + count] = &subinterpreter_client_self[subinterpreter_client_i]->_lf_updated_parameters.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add port subinterpreter.server.global_parameters to array of is_present fields.
            envs[subinterpreter_main].is_present_fields[3 + count] = &subinterpreter_server_self[0]->_lf_global_parameters.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port subinterpreter.server.global_parameters to array of intended_tag fields.
            envs[subinterpreter_main]._lf_intended_tag_fields[3 + count] = &subinterpreter_server_self[0]->_lf_global_parameters.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        // Reactor is a bank. Iterate over bank members.
        for (int subinterpreter_delay_i = 0; subinterpreter_delay_i < 1; subinterpreter_delay_i++) {
            // Add port subinterpreter.delay.out to array of is_present fields.
            envs[subinterpreter_main].is_present_fields[4 + count] = &subinterpreter_delay_self[0]->_lf_out.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add port subinterpreter.delay.out to array of intended_tag fields.
            envs[subinterpreter_main]._lf_intended_tag_fields[4 + count] = &subinterpreter_delay_self[0]->_lf_out.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance subinterpreter
    {
    
        // Set reaction priorities for ReactorInstance subinterpreter.client
        // Reactor is a bank. Iterate over bank members.
        for (int subinterpreter_client_i = 0; subinterpreter_client_i < 2; subinterpreter_client_i++) {
            subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            subinterpreter_client_self[subinterpreter_client_i]->_lf__reaction_1.index = 0xffffffffffff0001LL;
        }
    
    
        // Set reaction priorities for ReactorInstance subinterpreter.server
        {
            subinterpreter_server_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            subinterpreter_server_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            subinterpreter_server_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            subinterpreter_server_self[0]->_lf__reaction_1.index = 0xffffffffffff0002LL;
        }
    
    
        // Set reaction priorities for ReactorInstance subinterpreter.delay
        // Reactor is a bank. Iterate over bank members.
        for (int subinterpreter_delay_i = 0; subinterpreter_delay_i < 1; subinterpreter_delay_i++) {
            subinterpreter_delay_self[0]->_lf__reaction_0.chain_id = 1;
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            subinterpreter_delay_self[0]->_lf__reaction_0.index = 0xffffffffffff0000LL;
            subinterpreter_delay_self[0]->_lf__reaction_1.chain_id = 1;
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            subinterpreter_delay_self[0]->_lf__reaction_1.index = 0xffffffffffff0003LL;
        }
    
    }
    
    // Initialize the scheduler
    size_t num_reactions_per_level[4] = 
        {4, 2, 1, 1};
    sched_params_t sched_params = (sched_params_t) {
                            .num_reactions_per_level = &num_reactions_per_level[0],
                            .num_reactions_per_level_size = (size_t) 4};
    lf_sched_init(
        &envs[subinterpreter_main],
        envs[subinterpreter_main].num_workers,
        &sched_params
    );
    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&envs[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
#ifdef FEDERATED_CENTRALIZED
        _lf_logical_tag_complete(tag_to_send);
#endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void terminate_execution(environment_t* env) {}
#endif
